import type { ExternalTemplateMetadata, TemplateAnalysisResponse } from './types';
import { FieldType, PlaceholderSyntax } from './types';

export const MOCK_TEMPLATES: ExternalTemplateMetadata[] = [
  {
    id: 'tpl_invoice_v3',
    name: 'Счёт на оплату',
    description: 'Шаблон счёта для юридических лиц с автоматическим расчётом НДС и реквизитами',
    version: '3.0.1',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_invoice_v3.docx',
    tags: ['invoice', 'finance', 'юрлица'],
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-04-01T12:30:00Z',
    schema: {
      templateId: 'tpl_invoice_v3',
      templateName: 'Счёт на оплату',
      version: '3.0.1',
      placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
      totalPlaceholders: 12,
      fields: [
        {
          key: 'fullName',
          label: 'ФИО',
          type: FieldType.STRING,
          required: true,
          example: 'Иванов И.И.',
          description: 'Полное имя получателя счёта',
        },
        {
          key: 'amount',
          label: 'Сумма',
          type: FieldType.CURRENCY,
          required: true,
          example: 12500.5,
          description: 'Общая сумма к оплате',
        },
        {
          key: 'invoiceDate',
          label: 'Дата счёта',
          type: FieldType.DATE,
          required: true,
          example: '2026-04-01',
        },
        {
          key: 'companyName',
          label: 'Название компании',
          type: FieldType.STRING,
          required: true,
          example: 'ООО "Пример"',
        },
        { key: 'inn', label: 'ИНН', type: FieldType.STRING, required: true, example: '7707083893' },
        { key: 'kpp', label: 'КПП', type: FieldType.STRING, required: false, example: '770701001' },
        {
          key: 'bankAccount',
          label: 'Расчётный счёт',
          type: FieldType.STRING,
          required: true,
          example: '40702810000000000001',
        },
        { key: 'bik', label: 'БИК', type: FieldType.STRING, required: true, example: '044525225' },
        {
          key: 'vatRate',
          label: 'Ставка НДС',
          type: FieldType.NUMBER,
          required: false,
          example: 20,
          defaultValue: 20,
        },
        {
          key: 'serviceDescription',
          label: 'Описание услуг',
          type: FieldType.STRING,
          required: true,
          example: 'Услуги разработки ПО',
        },
        {
          key: 'dueDate',
          label: 'Срок оплаты',
          type: FieldType.DATE,
          required: false,
          example: '2026-04-15',
        },
        {
          key: 'contactEmail',
          label: 'Контактный email',
          type: FieldType.EMAIL,
          required: false,
          example: 'billing@example.com',
        },
      ],
    },
  },
  {
    id: 'tpl_contract_service',
    name: 'Договор оказания услуг',
    description: 'Стандартный договор для оформления B2B-услуг с гибкими условиями оплаты',
    version: '2.1.0',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_contract_service.docx',
    tags: ['contract', 'legal', 'b2b'],
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-03-15T09:45:00Z',
    schema: {
      templateId: 'tpl_contract_service',
      templateName: 'Договор оказания услуг',
      version: '2.1.0',
      placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
      totalPlaceholders: 18,
      fields: [
        {
          key: 'contractNumber',
          label: 'Номер договора',
          type: FieldType.STRING,
          required: true,
          example: 'КД-2026/001',
        },
        {
          key: 'contractDate',
          label: 'Дата договора',
          type: FieldType.DATE,
          required: true,
          example: '2026-04-01',
        },
        {
          key: 'clientName',
          label: 'Наименование клиента',
          type: FieldType.STRING,
          required: true,
        },
        { key: 'clientInn', label: 'ИНН клиента', type: FieldType.STRING, required: true },
        { key: 'executorName', label: 'Исполнитель', type: FieldType.STRING, required: true },
        {
          key: 'serviceDescription',
          label: 'Описание услуг',
          type: FieldType.STRING,
          required: true,
        },
        { key: 'totalAmount', label: 'Общая стоимость', type: FieldType.CURRENCY, required: true },
        {
          key: 'paymentTerms',
          label: 'Условия оплаты',
          type: FieldType.STRING,
          required: true,
          example: '5 рабочих дней',
        },
        { key: 'startDate', label: 'Дата начала', type: FieldType.DATE, required: true },
        { key: 'endDate', label: 'Дата окончания', type: FieldType.DATE, required: true },
      ],
    },
  },
  {
    id: 'tpl_nda_v1',
    name: 'Соглашение о конфиденциальности (NDA)',
    description: 'Шаблон NDA для защиты коммерческой тайны между двумя сторонами',
    version: '1.0.0',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_nda_v1.docx',
    tags: ['nda', 'legal', 'confidential'],
    createdAt: '2025-09-10T14:30:00Z',
    updatedAt: '2025-12-20T11:00:00Z',
    schema: {
      templateId: 'tpl_nda_v1',
      templateName: 'Соглашение о конфиденциальности',
      version: '1.0.0',
      placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
      totalPlaceholders: 8,
      fields: [
        { key: 'partyOneName', label: 'Первая сторона', type: FieldType.STRING, required: true },
        { key: 'partyTwoName', label: 'Вторая сторона', type: FieldType.STRING, required: true },
        { key: 'signingDate', label: 'Дата подписания', type: FieldType.DATE, required: true },
        {
          key: 'confidentialityPeriod',
          label: 'Срок конфиденциальности (лет)',
          type: FieldType.NUMBER,
          required: true,
          example: 3,
        },
        {
          key: 'jurisdiction',
          label: 'Юрисдикция',
          type: FieldType.STRING,
          required: false,
          example: 'РФ',
          defaultValue: 'РФ',
        },
        {
          key: 'subjectMatter',
          label: 'Предмет соглашения',
          type: FieldType.STRING,
          required: true,
        },
        { key: 'penaltyAmount', label: 'Размер штрафа', type: FieldType.CURRENCY, required: false },
        {
          key: 'arbitrationCity',
          label: 'Город арбитража',
          type: FieldType.STRING,
          required: false,
          example: 'Москва',
        },
      ],
    },
  },
  {
    id: 'tpl_offer_letter',
    name: 'Оффер для сотрудника',
    description: 'Письмо-предложение о трудоустройстве с указанием условий работы',
    version: '1.2.3',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_offer_letter.docx',
    tags: ['hr', 'offer', 'employment'],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-04-10T16:20:00Z',
    schema: {
      templateId: 'tpl_offer_letter',
      templateName: 'Оффер для сотрудника',
      version: '1.2.3',
      placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
      totalPlaceholders: 10,
      fields: [
        { key: 'candidateName', label: 'Имя кандидата', type: FieldType.STRING, required: true },
        { key: 'position', label: 'Должность', type: FieldType.STRING, required: true },
        { key: 'department', label: 'Отдел', type: FieldType.STRING, required: false },
        { key: 'salary', label: 'Оклад (руб.)', type: FieldType.CURRENCY, required: true },
        { key: 'startDate', label: 'Дата выхода', type: FieldType.DATE, required: true },
        {
          key: 'probationPeriod',
          label: 'Испытательный срок (мес.)',
          type: FieldType.NUMBER,
          required: false,
          example: 3,
        },
        { key: 'managerName', label: 'Руководитель', type: FieldType.STRING, required: true },
        {
          key: 'officeLocation',
          label: 'Офис',
          type: FieldType.STRING,
          required: false,
          example: 'Москва, Пресненская наб., 12',
        },
        { key: 'responseDeadline', label: 'Срок ответа', type: FieldType.DATE, required: true },
        { key: 'hrEmail', label: 'Email HR', type: FieldType.EMAIL, required: true },
      ],
    },
  },
  {
    id: 'tpl_act_completion',
    name: 'Акт выполненных работ',
    description: 'Акт сдачи-приёмки выполненных работ и услуг с приложениями',
    version: '2.0.0',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_act_completion.docx',
    tags: ['act', 'finance', 'completion'],
    createdAt: '2025-12-05T12:00:00Z',
    updatedAt: '2026-04-15T08:10:00Z',
  },
  {
    id: 'tpl_privacy_policy',
    name: 'Политика конфиденциальности',
    description: 'Шаблон политики конфиденциальности для веб-сервисов и приложений (GDPR/152-ФЗ)',
    version: '1.1.0',
    format: 'docx',
    downloadUrl: 'https://storage.example.com/tpl_privacy_policy.docx',
    tags: ['legal', 'privacy', 'gdpr'],
    createdAt: '2025-10-20T11:30:00Z',
    updatedAt: '2026-01-08T14:00:00Z',
    schema: {
      templateId: 'tpl_privacy_policy',
      templateName: 'Политика конфиденциальности',
      version: '1.1.0',
      placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
      totalPlaceholders: 6,
      fields: [
        { key: 'companyName', label: 'Название компании', type: FieldType.STRING, required: true },
        { key: 'companyAddress', label: 'Адрес компании', type: FieldType.STRING, required: true },
        { key: 'contactEmail', label: 'Email для запросов', type: FieldType.EMAIL, required: true },
        {
          key: 'effectiveDate',
          label: 'Дата вступления в силу',
          type: FieldType.DATE,
          required: true,
        },
        {
          key: 'retentionPeriod',
          label: 'Срок хранения данных (лет)',
          type: FieldType.NUMBER,
          required: true,
          example: 3,
        },
        {
          key: 'jurisdiction',
          label: 'Юрисдикция',
          type: FieldType.STRING,
          required: false,
          example: 'Российская Федерация',
        },
      ],
    },
  },
];

export const MOCK_ANALYSIS: TemplateAnalysisResponse = {
  schema: {
    templateId: 'tpl_new_upload',
    templateName: 'Новый шаблон',
    version: '1.0.0',
    placeholderSyntax: PlaceholderSyntax.DOUBLE_CURLY,
    totalPlaceholders: 7,
    fields: [
      {
        key: 'clientName',
        label: 'Клиент',
        type: FieldType.STRING,
        required: true,
        example: 'ООО "Клиент"',
      },
      { key: 'date', label: 'Дата', type: FieldType.DATE, required: true },
      { key: 'amount', label: 'Сумма', type: FieldType.CURRENCY, required: true },
      { key: 'email', label: 'Email', type: FieldType.EMAIL, required: false },
      { key: 'description', label: 'Описание', type: FieldType.STRING, required: true },
      { key: 'inn', label: 'ИНН', type: FieldType.STRING, required: false },
      { key: 'phone', label: 'Телефон', type: FieldType.PHONE, required: false },
    ],
  },
  warnings: [
    {
      code: 'LOW_CONFIDENCE_SCHEMA',
      message: "Тип поля 'date' определён эвристически, рекомендуется ручная проверка",
      field: 'date',
    },
  ],
  diagnostics: {
    parseTimeMs: 87,
    totalPlaceholders: 7,
    uniquePlaceholders: 7,
    duplicatePlaceholders: [],
    undocumentedKeys: [],
    syntaxIssues: [],
  },
};
